name: townyAI
version: '0.2.0'
main: town.sheepy.townyAI.TownyAI
api-version: '1.21'

commands:
  createtown:
    description: Create a Towny town at a specific chunk coordinate
    usage: /createtown <x> <z>
  ack:
    description: acknowledgement for a bot workflow
    usage: /ack <code>

depend: [WorldEdit, Towny, TownyUtilities, FlagWar]
